Fix error message when linking to the wrong task kind (#225)
Right now, this prints the runtime kind, so if you have a dockerfile
task being linked to myscript.js, you get:

    Error: Cannot link "myscript.js" to a node task

This is confusing, since you don't see what task is expected. With this
change, you get:

    Error: Cannot link "wtf.js" to a dockerfile task