Add dom to tsclib to fix crash on e.g. `window` (#207)
This allows `typeof window === "undefined"` checks in code, which won't
otherwise compile in TS:

    error TS2304: Cannot find name 'window'

Also fixes a nil pointer crash when `resp` is nil because `build.Run`
errored.